name: pmd-net
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.11
  - pandas=2.2.0
  - networkx=3.2.1
  - requests=2.31.0
  - beautifulsoup4=4.12.2
  - gensim=4.3.3
  - tqdm=4.66.1

  # Dev
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - jupyterlab=4.0.5

  #- pip
  #- pip:
  #  - pybliometrics==3.6.0
  #  - scholarly==1.7.11
