name: pmd-net
channels:
  - conda-forge
  - defaults
dependencies:
  # Core
  - python=3.11
  - pandas=2.2.0
  - networkx=3.2.1
  - requests=2.31.0
  - tqdm=4.66.1

  # Dev
  - matplotlib=3.8.0
  - seaborn=0.12.2
  - jupyterlab=4.0.5

  - pip
  - pip:
    - FlagEmbedding==1.3.5
  #  - pybliometrics==3.6.0
  #  - scholarly==1.7.11
